project:
  type: website
  output-dir: _site
  preview:
    port: 5896
    browser: false
  render:
    - "*.qmd"
    - "!parts"
  resources:
    - "parts"
    - "content"

website:
  image: images/logo.png
  site-url: https://jhelvy.github.io/dtais-dataviz/
  repo-url: https://github.com/jhelvy/dtais-dataviz
  description: 'Slides and content for my 2022 NRT workshop on storytelling and data visualization.'
  search: false
  open-graph: true
  twitter-card:
    site: "@johnhelveston"
  navbar:
    background: primary
    left:
      - text: Home
        href: index.qmd
      - text: Storytelling
        href: storytelling.qmd
      - text: Visualizing Information
        href: visualizing-information.qmd
  page-footer:
    center:
      - text: 'DTAIS Workshop: Storytelling & Data Visualization (Summer 2022)<br><a href="https://www.jhelvy.com"><i class="fas fa-user"></i> Dr. John Paul Helveston</a> | <a href="mailto:jph@gwu.edu"><i class="fas fa-envelope"></i> jph@gwu.edu</a> | <a href="https://github.com/jhelvy/dtais-dataviz"><i class="fa fa-github"></i></a> | <a href="https://twitter.com/JohnHelveston"><i class="fa fa-twitter"></i></a><br><a href="LICENSE.html">LICENSE: CC-BY-SA <i class="fab fa-creative-commons"></i><i class="fab fa-creative-commons-by"></i><i class="fab fa-creative-commons-sa"></i></a>'

format:
  html:
    theme: lux
    css: styles.css
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    include-in-header: "_includes/header.html"


